#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Hibiki Iida
# SPDX-License-Identifier: BSD-3-Clause
import sys

def tonum(s):
    try:
        return int(s)
    except:
        return float(s)

total = 0
n = 1

for line in sys.stdin:
    line = line.rstrip()
    if line == '0':
        break
    ans = tonum(line)
    total += ans
    print(f"{n}項目: {ans}, 現在の総計: {total}")
    n = n + 1

print("最終総計:",total)
